name: Update Index HTML
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_DOCS_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate index.html
        run: |
          python generate_index.py
      - name: Setup GitHub CLI
        run: |
          gh auth setup-git
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.API_DOCS_TOKEN }}
      - name: Commit and push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update index.html"
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.API_DOCS_TOKEN }}
